### ISSUE TITLE
Ability to use external diff tool

### ISSUE THREAD

**Issue by okgolove** [shini4i/argo-compare#13]
For example https://github.com/so-fancy/diff-so-fancy
It support unified diff output

**Comment by shini4i** [comment]
That's a good idea. You can try the following approach with 0.0.7 version:
`ARGO_COMPARE_DIFF_COMMAND="/usr/bin/diff -u %s %s | diff-so-fancy"  argo-compare branch <branch_name>`

Although with the tool from the example, you will always get the "renamed: %s to %" output due to the specifics of manifests rendering logic.

**Comment by okgolove** [comment]
Works fine, thanks!
